// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Partners.Api.Infrastructure;

#nullable disable

namespace Partners.Api.Infrastructure.Migrations
{
    [DbContext(typeof(PartnersDbContext))]
    partial class PartnersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Partners.Api.Domain.User", b =>
                {
                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("ParentExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("parent_external_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("ltree")
                        .HasColumnName("path");

                    b.HasKey("ExternalId")
                        .HasName("pk_users");

                    b.HasIndex("ParentExternalId")
                        .HasDatabaseName("ix_users_parent_external_id");

                    b.HasIndex("Path")
                        .HasDatabaseName("ix_users_path");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Path"), "gist");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_external_id_format", "external_id ~ '^[A-Za-z0-9_]{1,64}$'");
                        });
                });

            modelBuilder.Entity("Partners.Api.Domain.User", b =>
                {
                    b.HasOne("Partners.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ParentExternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_parent_external_id");
                });
#pragma warning restore 612, 618
        }
    }
}
