<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Activity.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BuildingBlocks.Contracts" Version="1.0.0" />
    <PackageReference Include="Grpc.Tools" Version="2.71.0" PrivateAssets="all" />
    <PackageReference Include="Google.Protobuf" Version="3.30.2" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.71.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\..\..\protos\commission\commission.proto" GrpcServices="Client" Link="Protos\commission.proto" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Activity.Tests" />
  </ItemGroup>
</Project>
