<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Partners.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\..\..\protos\partners\partners.proto" GrpcServices="Server" Link="Protos\partners.proto" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Partners.Tests" />
  </ItemGroup>
</Project>
