<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Commission.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BuildingBlocks.Contracts" Version="1.0.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.Net.ClientFactory" Version="2.71.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\..\..\protos\commission\commission.proto" GrpcServices="Server" Link="Protos\commission.proto" />
    <Protobuf Include="..\..\..\..\protos\partners\partners.proto" GrpcServices="Client" Link="Protos\partners.proto" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Commission.Tests" />
  </ItemGroup>
</Project>
